yatube/about/urls.py
from . import views
from django.urls import path


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_post, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}

yatube/templates/includes/footer.html
{% load static %}
<div class="footer-copyright text-center py-3">© {{ year }} Copyright
  <p title="Friendship is a magic"><span style="color:red">Ya</span>tube</p>
  <a href={% url 'about:author'%}> Об авторе </a>
  <h3>(▽◕ ᴥ ◕▽)</h3>
  <a href={% url 'about:tech'%}> Технологии </a>
</div>  

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<meta charset="utf-8"> 
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="/">
      <img src="{% static 'img/logo.png' %}" width="30"
      height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    {% if user.is_authenticated %}
    <a type="button" class="btn btn-outline-light"
      href="{% url 'posts:profile' user.username %}">
        Пользователь: {{ user.username }}
    </a>
    {% endif %}
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" 
        type="button" data-bs-toggle="dropdown" 
        aria-expanded="false">
        Навигация
      </button>
      <ul class="dropdown-menu">
        <li> 
          <a class="dropdown-item 
            {% if view_name  == 'about:author' %}
              active
            {% endif %}" 
            href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li>
          <a class="dropdown-item 
            {% if view_name  == 'about:tech' %}
              active
            {% endif %}"  
            href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
          <li> 
            <a class="dropdown-item
            {% if view_name  == 'posts:post_create' %}
              active
            {% endif %}" 
              href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <li> 
            <a class="dropdown-item
              {% if view_name  == 'users:password_change_form' %}
                active
              {% endif %}" 
              href="{% url 'users:password_change_form' %}">Изменить пароль</a>
          </li>
          <li> 
            <a class="dropdown-item
              {% if view_name  == 'users:logout' %}
                active
              {% endif %}" 
              href="{% url 'users:logout' %}">Выйти</a>
          </li>
          {% else %}
          <li> 
            <a class="dropdown-item
              {% if view_name  == 'users:login' %}
                active
              {% endif %}" 
              href="{% url 'users:login' %}">Войти</a>
          </li>
          <li> 
            <a class="dropdown-item
              {% if view_name  == 'users:signup' %}
                active
              {% endif %}" 
              href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
    </div>  
  </div>
</nav>   
{% endwith %}